import { Activity, Archive, ArrowUpRight, CarFront, Check, Copy, Download, MapPin, MoreHorizontal, Phone, Plus, Printer, QrCode, RefreshCw, ScanLine, ShieldCheck, Smartphone, Trash2, X } from 'lucide-react';
import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useCreateQrCode, useDeleteQrCode, useGetStats, useListQrCodes, useListScanLogs, useUpdateQrCode, getGetStatsQueryKey, getListQrCodesQueryKey, getListScanLogsQueryKey } from '@workspace/api-client-react';
import { QrVisual } from '@/components/qr-visual';

type QrForm = { label: string; location: string; forwardPhone: string };

const initialForm: QrForm = { label: '', location: '', forwardPhone: '' };
const formatTime = (date: string) => new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(date));

function Skeleton({ className = '' }: { className?: string }) { return <div className={`animate-pulse rounded-md bg-[hsl(var(--muted))] ${className}`} />; }

function Metric({ label, value, detail, icon: Icon, tone = 'dark' }: { label: string; value: string | number; detail: string; icon: typeof Activity; tone?: 'dark' | 'yellow' | 'teal' }) {
  const box = tone === 'yellow' ? 'bg-[hsl(var(--accent))] text-[hsl(var(--accent-foreground))]' : tone === 'teal' ? 'bg-[hsl(var(--chart-2))] text-[hsl(var(--card))]' : 'bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]';
  return <div className={`relative overflow-hidden rounded-xl p-5 ${box} transition duration-300 hover:-translate-y-1 hover:shadow-[var(--shadow-lg)]`}><div className="absolute -right-6 -top-8 h-28 w-28 rounded-full border-[14px] border-current opacity-[.07]" /><div className="flex items-start justify-between"><span className="font-mono-custom text-[10px] uppercase tracking-[.16em] opacity-65">{label}</span><Icon className="h-4 w-4 opacity-65" /></div><p className="mt-7 text-[32px] font-extrabold leading-none tracking-[-.06em]">{value}</p><p className="mt-2 text-[11px] opacity-65">{detail}</p></div>;
}

function QrDialog({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) {
  const create = useCreateQrCode();
  const [form, setForm] = useState(initialForm);
  const [error, setError] = useState('');
  const submit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setError('');
    create.mutate({ data: { label: form.label, location: form.location, forwardPhone: form.forwardPhone || null } }, {
      onSuccess: () => { onCreated(); onClose(); },
      onError: () => setError('We could not create that code. Check the details and try again.'),
    });
  };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-[hsl(var(--primary)/.45)] p-4 backdrop-blur-sm" role="dialog" aria-modal="true" data-testid="dialog-create-qr">
    <div className="w-full max-w-[500px] overflow-hidden rounded-2xl bg-[hsl(var(--card))] shadow-[var(--shadow-2xl)] rise-in">
      <div className="flex items-start justify-between border-b border-[hsl(var(--border))] px-6 py-5"><div><p className="font-mono-custom text-[10px] uppercase tracking-[.18em] text-[hsl(var(--chart-2))]">New vehicle code</p><h2 className="mt-1 text-xl font-extrabold tracking-[-.04em]">Put a code where it counts.</h2></div><button type="button" onClick={onClose} data-testid="button-close-create-qr" className="rounded-lg p-2 text-[hsl(var(--muted-foreground))] hover:bg-[hsl(var(--muted))]"><X className="h-4 w-4" /></button></div>
      <form onSubmit={submit} className="space-y-5 p-6">
        <div className="rounded-xl bg-[hsl(var(--accent)/.12)] p-4 text-xs leading-5 text-[hsl(var(--foreground)/.72)]"><ShieldCheck className="mr-2 inline h-4 w-4 text-[hsl(var(--chart-2))]" />The forwarding number is optional. You can add or change it later in Settings.</div>
        <label className="block"><span className="mb-2 block text-xs font-bold">Code label</span><input required value={form.label} onChange={(e) => setForm({ ...form, label: e.target.value })} data-testid="input-qr-label" className="h-11 w-full rounded-lg border border-[hsl(var(--input))] bg-[hsl(var(--background))] px-3 text-sm outline-none focus:border-[hsl(var(--accent))] focus:ring-4 focus:ring-[hsl(var(--accent)/.13)]" placeholder="e.g. Blue Subaru" /></label>
        <label className="block"><span className="mb-2 block text-xs font-bold">Usual location</span><input required value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} data-testid="input-qr-location" className="h-11 w-full rounded-lg border border-[hsl(var(--input))] bg-[hsl(var(--background))] px-3 text-sm outline-none focus:border-[hsl(var(--accent))] focus:ring-4 focus:ring-[hsl(var(--accent)/.13)]" placeholder="e.g. Home driveway" /></label>
        <label className="block"><span className="mb-2 block text-xs font-bold">Forwarding number <span className="font-normal text-[hsl(var(--muted-foreground))]">(optional)</span></span><input value={form.forwardPhone} onChange={(e) => setForm({ ...form, forwardPhone: e.target.value })} data-testid="input-qr-phone" type="tel" className="h-11 w-full rounded-lg border border-[hsl(var(--input))] bg-[hsl(var(--background))] px-3 text-sm outline-none focus:border-[hsl(var(--accent))] focus:ring-4 focus:ring-[hsl(var(--accent)/.13)]" placeholder="+1 555 010 2040" /></label>
        {error && <p className="text-xs text-[hsl(var(--destructive))]" data-testid="status-create-error">{error}</p>}
        <div className="flex justify-end gap-3 pt-1"><button type="button" onClick={onClose} data-testid="button-cancel-create-qr" className="rounded-lg px-4 py-2.5 text-xs font-bold text-[hsl(var(--muted-foreground))] hover:bg-[hsl(var(--muted))]">Cancel</button><button type="submit" disabled={create.isPending} data-testid="button-save-qr" className="rounded-lg bg-[hsl(var(--primary))] px-5 py-2.5 text-xs font-bold text-[hsl(var(--primary-foreground))] transition hover:-translate-y-0.5 disabled:opacity-60">{create.isPending ? 'Creating code…' : 'Create code'}</button></div>
      </form>
    </div>
  </div>;
}

function QrCard({ qr, onRefresh }: { qr: { id: number; label: string; location: string; active: boolean; createdAt: string; forwardPhone?: string | null }; onRefresh: () => void }) {
  const queryClient = useQueryClient();
  const update = useUpdateQrCode();
  const remove = useDeleteQrCode();
  const [confirm, setConfirm] = useState(false);
  const toggle = () => update.mutate({ id: qr.id, data: { active: !qr.active } }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListQrCodesQueryKey() }); } });
  const del = () => remove.mutate({ id: qr.id }, { onSuccess: () => { setConfirm(false); onRefresh(); } });
  const copyLink = () => { navigator.clipboard?.writeText(`${window.location.origin}/scan/${qr.id}`); };
  return <article className={`group relative flex flex-col overflow-hidden rounded-xl border bg-[hsl(var(--card))] transition duration-300 hover:-translate-y-1 hover:shadow-[var(--shadow-lg)] ${qr.active ? 'border-[hsl(var(--border))]' : 'border-dashed border-[hsl(var(--muted-foreground)/.35)] opacity-75'}`} data-testid={`card-qr-${qr.id}`}>
    <div className="flex items-start justify-between px-5 pt-5"><div className="flex min-w-0 items-center gap-3"><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-lg ${qr.active ? 'bg-[hsl(var(--accent)/.22)] text-[hsl(var(--foreground))]' : 'bg-[hsl(var(--muted))] text-[hsl(var(--muted-foreground))]'}`}><QrCode className="h-[18px] w-[18px]" /></div><div className="min-w-0"><h3 className="truncate text-sm font-extrabold">{qr.label}</h3><p className="mt-0.5 flex items-center gap-1 truncate text-[11px] text-[hsl(var(--muted-foreground))]"><MapPin className="h-3 w-3" />{qr.location}</p></div></div><div className="relative"><button type="button" onClick={() => setConfirm(!confirm)} aria-label={`Manage ${qr.label}`} data-testid={`button-manage-qr-${qr.id}`} className="rounded-md p-1.5 text-[hsl(var(--muted-foreground))] hover:bg-[hsl(var(--muted))]"><MoreHorizontal className="h-4 w-4" /></button>{confirm && <div className="absolute right-0 top-9 z-10 w-40 rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-1.5 shadow-[var(--shadow-lg)]"><button type="button" onClick={toggle} data-testid={`button-toggle-qr-${qr.id}`} className="flex w-full items-center gap-2 rounded-md px-2.5 py-2 text-left text-[11px] font-semibold hover:bg-[hsl(var(--muted))]">{qr.active ? <Archive className="h-3.5 w-3.5" /> : <Check className="h-3.5 w-3.5" />}{qr.active ? 'Pause code' : 'Activate code'}</button><button type="button" onClick={del} data-testid={`button-delete-qr-${qr.id}`} className="flex w-full items-center gap-2 rounded-md px-2.5 py-2 text-left text-[11px] font-semibold text-[hsl(var(--destructive))] hover:bg-[hsl(var(--destructive)/.08)]"><Trash2 className="h-3.5 w-3.5" />Delete code</button></div>}</div></div>
    <div className="flex items-center justify-center px-5 py-5"><QrVisual id={qr.id} compact /></div>
    <div className="mt-auto border-t border-[hsl(var(--border))] px-5 py-3.5"><div className="mb-3 flex items-center justify-between"><span className={`inline-flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-[.12em] ${qr.active ? 'text-[hsl(var(--chart-2))]' : 'text-[hsl(var(--muted-foreground))]'}`}><span className={`h-1.5 w-1.5 rounded-full ${qr.active ? 'bg-[hsl(var(--chart-2))]' : 'bg-[hsl(var(--muted-foreground))]'}`} />{qr.active ? 'Active' : 'Paused'}</span><span className="font-mono-custom text-[10px] text-[hsl(var(--muted-foreground))]">ID {String(qr.id).padStart(4, '0')}</span></div><div className="flex gap-2"><button type="button" onClick={copyLink} data-testid={`button-copy-qr-${qr.id}`} className="flex flex-1 items-center justify-center gap-1.5 rounded-md border border-[hsl(var(--border))] py-2 text-[10px] font-bold transition hover:border-[hsl(var(--accent))] hover:bg-[hsl(var(--accent)/.1)]"><Copy className="h-3 w-3" />Copy link</button><button type="button" onClick={() => window.print()} data-testid={`button-print-qr-${qr.id}`} className="grid w-9 place-items-center rounded-md border border-[hsl(var(--border))] text-[hsl(var(--muted-foreground))] hover:bg-[hsl(var(--muted))]"><Printer className="h-3.5 w-3.5" /></button></div></div>
  </article>;
}

export default function Dashboard({ username }: { username?: string | null }) {
  const queryClient = useQueryClient();
  const [showCreate, setShowCreate] = useState(false);
  const qrs = useListQrCodes();
  const stats = useGetStats();
  const logs = useListScanLogs({ limit: 8 });
  const refresh = () => { queryClient.invalidateQueries({ queryKey: getListQrCodesQueryKey() }); queryClient.invalidateQueries({ queryKey: getGetStatsQueryKey() }); queryClient.invalidateQueries({ queryKey: getListScanLogsQueryKey({ limit: 8 }) }); };
  const error = qrs.isError || stats.isError || logs.isError;
  const qrItems = qrs.data || [];
  const statData = stats.data;
  return <div className="rise-in">
    <div className="mb-10 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 flex items-center gap-2 font-mono-custom text-[10px] font-medium uppercase tracking-[.2em] text-[hsl(var(--chart-2))]"><span className="h-1.5 w-1.5 rounded-full bg-[hsl(var(--chart-2))]" />Owner dashboard</p><h1 className="text-3xl font-extrabold tracking-[-.06em] md:text-[40px]">Good to see you, <span className="text-[hsl(var(--muted-foreground))]">{username?.split('@')[0] || 'driver'}.</span></h1><p className="mt-3 max-w-xl text-sm text-[hsl(var(--muted-foreground))]">Your roadside contact network, at a glance.</p></div><button type="button" onClick={() => setShowCreate(true)} data-testid="button-add-qr" className="group inline-flex h-11 items-center justify-center gap-2 rounded-lg bg-[hsl(var(--primary))] px-4 text-xs font-bold text-[hsl(var(--primary-foreground))] shadow-[var(--shadow-xs)] transition hover:-translate-y-0.5 hover:shadow-[var(--shadow-md)]"><Plus className="h-4 w-4 transition group-hover:rotate-90" />Add a vehicle code</button></div>
    {error && <div role="alert" className="mb-6 flex items-center justify-between rounded-xl border border-[hsl(var(--destructive)/.25)] bg-[hsl(var(--destructive)/.06)] px-4 py-3 text-xs text-[hsl(var(--destructive))]" data-testid="status-dashboard-error"><span>Some dashboard data could not be loaded.</span><button type="button" onClick={refresh} data-testid="button-retry-dashboard" className="inline-flex items-center gap-1.5 font-bold"><RefreshCw className="h-3.5 w-3.5" />Retry</button></div>}
    <section className="mb-10 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      {stats.isLoading ? <>{[1,2,3,4].map((i) => <Skeleton key={i} className="h-[140px]" />)}</> : <><Metric label="Vehicle codes" value={statData?.totalQrCodes ?? qrItems.length} detail={`${statData?.activeQrCodes ?? qrItems.filter((q) => q.active).length} currently active`} icon={QrCode} tone="yellow" /><Metric label="Total scans" value={statData?.totalScans ?? 0} detail="All-time contact attempts" icon={ScanLine} tone="dark" /><Metric label="Calls connected" value={statData?.totalCalls ?? 0} detail="Private conversations" icon={Phone} tone="teal" /><Metric label="Texts sent" value={statData?.totalTexts ?? 0} detail="Direct contact requests" icon={Smartphone} tone="dark" /></>}
    </section>
    <div className="grid gap-8 xl:grid-cols-[1.35fr_.65fr]">
      <section><div className="mb-4 flex items-end justify-between"><div><h2 className="text-lg font-extrabold tracking-[-.035em]">Your vehicle codes</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Print one for each car, or each place you park it.</p></div>{qrItems.length > 0 && <span className="font-mono-custom text-[10px] text-[hsl(var(--muted-foreground))]">{qrItems.length} {qrItems.length === 1 ? 'code' : 'codes'}</span>}</div>{qrs.isLoading ? <div className="grid gap-4 sm:grid-cols-2"><Skeleton className="h-[315px]" /><Skeleton className="h-[315px]" /></div> : qrItems.length === 0 ? <div className="app-grid flex min-h-[300px] flex-col items-center justify-center rounded-xl border border-dashed border-[hsl(var(--border))] bg-[hsl(var(--card)/.45)] px-6 text-center"><div className="mb-4 grid h-12 w-12 place-items-center rounded-xl bg-[hsl(var(--accent)/.22)]"><CarFront className="h-5 w-5" /></div><h3 className="text-sm font-extrabold">No vehicle codes yet</h3><p className="mt-2 max-w-xs text-xs leading-5 text-[hsl(var(--muted-foreground))]">Create your first code and place it on the dashboard or windshield of your car.</p><button type="button" onClick={() => setShowCreate(true)} data-testid="button-empty-add-qr" className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[hsl(var(--primary))] px-4 py-2.5 text-xs font-bold text-[hsl(var(--primary-foreground))]"><Plus className="h-3.5 w-3.5" />Create first code</button></div> : <div className="grid gap-4 sm:grid-cols-2">{qrItems.map((qr) => <QrCard key={qr.id} qr={qr} onRefresh={refresh} />)}</div>}</section>
      <section><div className="mb-4 flex items-end justify-between"><div><h2 className="text-lg font-extrabold tracking-[-.035em]">Recent activity</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">The last few times someone reached out.</p></div><Activity className="mb-1 h-4 w-4 text-[hsl(var(--muted-foreground))]" /></div><div className="overflow-hidden rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))]">{logs.isLoading ? <div className="space-y-5 p-5">{[1,2,3,4].map((i) => <div key={i} className="flex gap-3"><Skeleton className="h-8 w-8 rounded-full" /><div className="flex-1 space-y-2"><Skeleton className="h-3 w-2/3" /><Skeleton className="h-2 w-1/3" /></div></div>)}</div> : (logs.data || statData?.recentLogs || []).length === 0 ? <div className="flex min-h-[250px] flex-col items-center justify-center px-6 text-center"><div className="mb-4 grid h-11 w-11 place-items-center rounded-full bg-[hsl(var(--muted))]"><Activity className="h-4 w-4 text-[hsl(var(--muted-foreground))]" /></div><p className="text-sm font-bold">Quiet for now</p><p className="mt-2 max-w-[220px] text-xs leading-5 text-[hsl(var(--muted-foreground))]">When someone scans a code, their visit will appear here.</p></div> : <div className="divide-y divide-[hsl(var(--border))]">{(logs.data || statData?.recentLogs || []).slice(0, 8).map((log, index) => <div key={log.id} className="flex items-center gap-3 px-4 py-4 transition hover:bg-[hsl(var(--muted)/.45)]" data-testid={`row-activity-${log.id}`}><div className={`grid h-8 w-8 shrink-0 place-items-center rounded-full ${log.action === 'call' ? 'bg-[hsl(var(--chart-2)/.12)] text-[hsl(var(--chart-2))]' : log.action === 'text' ? 'bg-[hsl(var(--accent)/.2)] text-[hsl(var(--foreground))]' : 'bg-[hsl(var(--muted))] text-[hsl(var(--muted-foreground))]'}`}>{log.action === 'call' ? <Phone className="h-3.5 w-3.5" /> : log.action === 'text' ? <Smartphone className="h-3.5 w-3.5" /> : <ScanLine className="h-3.5 w-3.5" />}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{log.action === 'scan' ? 'Code scanned' : log.action === 'call' ? 'Call request' : 'Text request'}</p><p className="mt-1 truncate text-[10px] text-[hsl(var(--muted-foreground))]">{log.label || `Vehicle code ${log.qrCodeId}`}</p></div><span className="shrink-0 font-mono-custom text-[9px] text-[hsl(var(--muted-foreground))]">{formatTime(log.scannedAt)}</span></div>)}</div>}</div></section>
    </div>
    <div className="mt-10 flex flex-col justify-between gap-3 rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--secondary)/.45)] px-5 py-4 text-xs sm:flex-row sm:items-center"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-[hsl(var(--chart-2))]" /><div><p className="font-bold">Your privacy is the point.</p><p className="mt-0.5 text-[hsl(var(--muted-foreground))]">Visitors see a safe contact page, never your personal details.</p></div></div><button type="button" data-testid="button-learn-privacy" className="inline-flex items-center gap-1 font-bold underline decoration-[hsl(var(--accent))] underline-offset-4">How it works <ArrowUpRight className="h-3.5 w-3.5" /></button></div>
    {showCreate && <QrDialog onClose={() => setShowCreate(false)} onCreated={refresh} />}
  </div>;
}